List advanceFlutterExam1 = [
  "1. what is Flutter?",
  "2. what is Dart?",
  "3. what is Widget?",
  "4. What are the major deference between stateful & stateless widget?",
  "5. what is state?",
  "6. what is OOP?",
  "7. what is data encapsulation?(in form of what, why & how).",
  "8. what is inheritance?(in form of what, why & how).",
  "9. what is data abstraction?(in form of what, why & how).",
  "10. what is polymorphism?(in form of what, why & how).",
  "11. what is API & Server?",
  "12. Explain process of API calling. (step by step process)",
  "13. What is JSON? (what, why, how)",
  "14. How to manage state using provider? (what, why, how)",
  "15. How to expand size of widget?",
  "16. What is return type of build method?",
  "17. How to update state in stateful widget in flutter?",
  "18. How to generate List in Flutter/Dart?",
  "19. What is use Container widget?",
  "20. What is state management?",
  "21. What are differences between Timer() and Future.delay()?",
  "22. What are differences between synchronous & asynchronous programming?",
  "23. What is use of Spacer() widget?",
  "24. What is JSON parsing? (what, why, how)",
  "25. Which package is used store local-small amount of data? How(give methods name)?",
  "26. Which package is used to open URL in application?",
  "27. What is use of notifylistener() method?",
  "28. Give one-line detail of every status code?",
  "29. How many HTTP request exist while API calling and which are?",
  "30. What is Model class? (what, why, how)",
];



