List php_questions_list = [
  "1. What is PHP? (What, Why, How)",
  "2. What is an API? Explain its purpose and how PHP interacts with APIs.",
  "3. What is a server? Explain its role in web development.",
  "4. What is JSON? How is it used in PHP?",
  "5. What is SQL? Provide its basic functions and use cases.",
  "6. What are phpMyAdmin and XAMPP? Explain their purpose and how they are used in PHP development.",
  "7. What is Bootstrap? How can it be integrated into a PHP project?",
  "8. Explain arrays in PHP. Provide examples of indexed, associative, and multidimensional arrays.",
  "9. Explain different types of loops in PHP. Provide examples for for, while, do-while, and foreach.",
  "10. How do you connect a database to PHP? Provide code for a basic MySQL connection.",
  "11. Write a function to update user details in PHP using SQL. Include proper syntax and parameters.",
  "12. Explain the difference between echo and print in PHP.",
  "13. What is the purpose of the header() function in PHP? Provide an example.",
  "14. How do you include a file in PHP? Explain the difference between include and require.",
  "15. What are PHP superglobal variables? List five examples and explain their use.",
  "16. How is \$_POST different from \$_GET? Provide a use case for each.",
  "17. What is the purpose of the \$_FILES superglobal? Explain its structure and usage.",
  "18. What does the isset() function do? How is it different from empty()?",
  "19. Write PHP code to access an array using a foreach loop.",
  "20. How would you check if a specific key exists in an associative array?",
  "21. Write an SQL query to select all records where age is greater than 30 from a table called users.",
  "22. What is the purpose of the mysqli_fetch_assoc() function in PHP? How does it differ from mysqli_fetch_array()?",
  "23. Write PHP code to create an insertion API, including a configuration file.",
  '''24. What is the purpose of the following PHP functions?,
  file_get_contents()
  http_response_code()
  count()''',
];
